Pull request к РК №1
java-park-mail-ru/tron-09-2016 pull request #1
Opened 2016-10-04 16:19 UTC by BOG8

Здравствуйте, проверьте пожалуйста наш pull request.
Из недочётов: в файле UserController.java над функцией изменения данных пользователя (changeUserInfo) горит инспекция "Overly compex method". Критично ли её нахождение?

2016-10-04 21:47 UTC, KSolovyev requested changes

2016-10-04 21:47 UTC, KSolovyev commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Это файл локальных настроек среды и он должен быть в .gitignore. Не забудьте удалить его из репозитория

2016-10-04 21:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/AuthorizationController.java
> +            return ResponseEntity.ok("{\n\t\"id\": " + Long.toString(user.getID()) + "\n}");
Сложно читать. Давайте напишем `"{\"id\": " + user.getId() + '}'`

2016-10-04 21:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/AuthorizationController.java
> +            return ResponseEntity.ok("{\n\t\"id\": " + Long.toString(user.getID()) + "\n}");
и тут тоже

2016-10-04 21:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        return ResponseEntity.ok("{\n\t\"id\": " + Long.toString(newUser.getID()) + "\n}");
и тут тоже

2016-10-04 21:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/UserController.java
> +    private final String badResponse =
Давайте делать это все-таки через сериализуемый класс. Кроме того, нужно избавится от русского текста в сообщениях. Привыкайте к тому, что языков может быть несколько и вы должны уметь показывать сообщения на нескольких. Переделывать одноязычный сервер в многоязычный - это боль. Поэтому вместо сообщения должен быть код ошибки или же ключ локализации (по которому фронт сможет найти нужное сообщение). Ну и в завершение, все константы должны быть static. Т.е. в итоге должно получиться что-то вроде
`private final static BadResponse BAD_RESPONSE = new BadResponse(403, "localization.access_denied")`
или
`private final static BadResponse BAD_RESPONSE = new BadResponse(403, ErrorCodes.AccessDenied.getCode())`

2016-10-04 21:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/UserController.java
> +                '}');
Нет, так делать нельзя. Если вам не нравится идея использовать Jackson для сериализации в JSON, используйте GSON  или любую другую библиотеку, которая уберет необходимость вручную набирать структуру JSON-сообщения

2016-10-04 21:47 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/UserController.java
> +        if (sessionUser.getID() != userId){
А почему один пользователь не может ничего узнать о другом пользователе?

2016-10-04 21:56 UTC, KSolovyev requested changes
Папка /target/ должна лежать в .gitignore. Не забудьте удалить ее из проекта

2016-10-04 21:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/UserController.java
> +            sessionUser.setLogin(login);
Есть ли гарантия, что данные этого пользователя, но залогиненного в другой сессии так же изменятся после этого?

2016-10-04 21:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/UserController.java
> +        sessionService.deleteSession(httpSession.getId());
Аналогичный вопрос, что будет с другими сессиями этого пользователя?

2016-10-04 21:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/AccountService.java
> +        for(Map.Entry<String, UserProfile> entry : userNameToUser.entrySet()) {
Эта функция должна работать за О(1)

2016-10-05 11:05 UTC, KSolovyev commented
Еще у вас .idea/libraries в .gitignore, но в проект эти файлы все равно пролезли. Это может поломать проект, так что удаляйте их

2016-10-05 16:11 UTC, KSolovyev requested changes

2016-10-05 16:11 UTC, KSolovyev commented on tp_java_new.xml
> +<?xml version="1.0" encoding="UTF-8"?>
B еще одно. Вот этого файла быть в репозитории не должно. Вы его импортировали, он уже есть во внутренних файлах idea

2016-10-05 16:14 UTC, BOG8 commented on src/main/java/ru/mail/park/main/UserController.java
> +            sessionUser.setLogin(login);
Судя по коду, да. Должны измениться все сессии. Так как в HashMap при нескольких сессиях одного и того же пользователя для каждой сессии будет храниться объект UserPrifile, который расположен в AccauntService. Если я недостаточно корректно сейчас изъясняюсь, то могу попробовать объяснить на самом рк)

2016-10-05 16:24 UTC, BOG8 commented on src/main/java/ru/mail/park/main/UserController.java
> +        sessionService.deleteSession(httpSession.getId());
В данном случае удалиться только одна сессия. Сейчас перепишу так, чтобы удалились все сессии пользователя

2016-10-05 16:27 UTC, BOG8 commented on src/main/java/ru/mail/park/main/UserController.java
> +        if (sessionUser.getID() != userId){
Исправил, теперь можно узнать информацию о любом пользователе

2016-10-05 17:50 UTC, BOG8 commented
Проверьте pull request ещё раз, пожалуйста :)

2016-10-06 12:56 UTC, KSolovyev requested changes

2016-10-06 12:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/UserController.java
> +            return ResponseEntity.ok(
Сделайте здесь, как и в другом контроллере. И вообще хорошо бы эту процедуру вынести в хелпер:
```
public static String getIdResponse(int id) {
     return "{....";
}

2016-10-06 12:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/AccountService.java
> +        if (userNameToUser.containsKey(login))
просто `return userNameToUser.get(login)`

2016-10-06 12:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/SessionService.java
> +        Vector<String> userSessions = new Vector<>();
ArrayList<String>

Vector - это синхронизированная коллекция

2016-10-06 12:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/SessionService.java
> + * ДЗ: реализовать класс, который по соответствующему id сессии будет отдавать пользователей(т.е. реализовать авторизацию по сессии)
надо убрать комментарий

2016-10-06 12:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/AccountService.java
> +        if (userNameToUser.containsKey(login))
просто `userNameToUser.remove(login);`

2016-10-06 13:49 UTC, BOG8 commented
Код исправлен в соответствии с вашими коментариями

2016-10-06 18:57 UTC, BOG8 commented
Надеюсь, что это последняя правка в этом pull request'е)

2016-10-07 08:47 UTC, KSolovyev approved these changes

2016-10-07 08:47 UTC, merged