Pull request к РК №2
java-park-mail-ru/tron-09-2016 pull request #2
Opened 2016-10-22 17:45 UTC by BOG8

Здравствуйте, я выполнил все работы ко второму РК (наивность), кроме тестов. Тесты будет делать мой коллега. Не могли бы вы посмотреть мою часть работы и указать на места в коде, которые требуют улучшения.

2016-10-23 12:51 UTC, isopov requested changes
Спешу, посмотрел еще не всё, но переделывать тут надо практически всё, так что можно уже начать.

И советую переделку начать с тестов - написать тесты, убедиться, что они проходят, переделать, убедиться, что тесты всё также проходят.

2016-10-23 12:51 UTC, isopov commented on .idea/dataSources/820ecd63-cb95-4a81-a365-922de73d992d.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл надо удалить. Перед этим нажмите в настройках этого коннекшна в базе в Идее "make global" или как-то так. Тогда он станет принадлежать Идее вообще, а не этому конкретному проекту.

2016-10-23 12:51 UTC, isopov commented on .idea/sqldialects.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Аналогично и этот файл надо удалить и вообще .idea папку всю заигнорить

2016-10-23 12:51 UTC, isopov commented on L1.3.iml
>      </content>
И этот файл надо заигнорить и удалить.

2016-10-23 12:51 UTC, isopov commented on pom.xml
> +            <groupId>org.springframework</groupId>
Удалите эту зависимость - она должна прилетать от соответствующий зависимостей более высокого уровня (spring-boot-starter-*)

2016-10-23 12:51 UTC, isopov commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
И эту зависимость удалите.

2016-10-23 12:51 UTC, isopov commented on pom.xml
> +            <groupId>com.google.code.gson</groupId>
Вы используете gson?

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/controllers/BaseController.java
> +    protected final DataSource dataSource;
Контроллер не должен зависеть от базы. Он должен зависить только от сервисов

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/controllers/UserController.java
> +        userDAO = new UserDAOImpl(dataSource);
ДАО (Сервис, Репозиторий) должен создавать спринг, а не вы.

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/dao/AuthorizationDAO.java
> +    ResponseEntity login(String jsonString, HttpSession httpSession);
ДАО, не должно возвращать web-объекты. О сессии оно тоже ничего не должно знать. Может это у вас вообще не ДАО?

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +        final JsonObject jsonObject = new JsonParser().parse(jsonString).getAsJsonObject();
давайте не будем тащить вторую json-библиотеку, а ограничимся одной. И пусть она нам сама автоматически парсит json в наши объекты.

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(BAD_RESPONSE);
Тут не хватает хотя бы логирования. Не говоря о том, что ДАО-слой не должен возвращать объекты из ВЕБ-слоя.

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +        final AuthorizationDAO authorizationDAO = new AuthorizationDAOImpl(dataSource);
Давайте у нас один ДАО будет зависеть от другого, а не создавать его.

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +        if (object instanceof SessionDataSet) {
эта логика явно не в том слое помещена

2016-10-23 12:51 UTC, isopov commented on src/main/java/ru/mail/park/services/DataBaseService.java
> +
Почему конфигурация называется "Сервис"?
Зачем вообще эта конфигурация нужна? Давайте удалим полностью и забудем, как страшный сон.

2016-10-23 13:20 UTC, BOG8 commented on pom.xml
> +            <groupId>com.google.code.gson</groupId>
Да

2016-10-23 13:24 UTC, BOG8 commented on src/main/java/ru/mail/park/services/DataBaseService.java
> +
Удалить весь файл? Но ведь я через него подключаюсь к базе

2016-10-23 16:06 UTC, BOG8 commented on .idea/dataSources/820ecd63-cb95-4a81-a365-922de73d992d.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Насчёт "make global" не понял, где и как это сделать. А в гитигнор файл отправил

2016-10-23 16:07 UTC, BOG8 commented on .idea/sqldialects.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Вся папка отправлена в гитигнор

2016-10-23 16:07 UTC, BOG8 commented on L1.3.iml
>      </content>
Файл отправлен в гитигнор

2016-10-23 16:16 UTC, BOG8 commented on pom.xml
> +            <groupId>org.springframework</groupId>
Удалил

2016-10-23 16:16 UTC, BOG8 commented on pom.xml
> +            <groupId>org.springframework.boot</groupId>
Удалил

2016-10-23 17:20 UTC, BOG8 commented on pom.xml
> +            <groupId>com.google.code.gson</groupId>
Теперь нет)

2016-10-23 17:21 UTC, BOG8 commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +        final JsonObject jsonObject = new JsonParser().parse(jsonString).getAsJsonObject();
Больше не тащу

2016-10-23 17:58 UTC, BOG8 commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +            return ResponseEntity.status(HttpStatus.FORBIDDEN).body(BAD_RESPONSE);
Логирования в виде System.out.println("") будет достаточно? Или стоит использовать что-то вроде Log4j... И вы хотите чтобы я логировал что-то конкретное или весь этот файл?

2016-10-23 21:59 UTC, BOG8 commented
Постарался выполнить все ваши замечания (которые смог осознать). Жду новых правок)))

2016-10-24 08:14 UTC, isopov requested changes

2016-10-24 08:14 UTC, isopov commented on .gitignore
> +/L1.3.iml
давайте заигнорим через *.iml

2016-10-24 08:14 UTC, isopov commented on pom.xml
> +            <groupId>org.hsqldb</groupId>
зачем эта зависимость, да еще и в рантайме?

2016-10-24 08:14 UTC, isopov commented on pom.xml
> +            <groupId>commons-dbcp</groupId>
Почему этот пул? Чем не понравился дефолтный? И я не вижу убирание дефолтного из зависимстей.

2016-10-24 08:14 UTC, isopov commented on src/main/java/ru/mail/park/DataBaseConnector.java
> +public class DataBaseConnector {
>Удалить весь файл? Но ведь я через него подключаюсь к базе

Да, я предлагаю именно удалить и подключаться стандартными средствами через application.properties

2016-10-24 08:14 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +    public UserDataSet getUserInfo(long userId, String sessionId) {
sessionId аргумент теперь не используется, так?

2016-10-24 08:14 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +    public UserDataSet changeUserInfo(long userId, UserDataSet changesForUser, String sessionId) {
И здесь тоже sessionId не используется

2016-10-24 08:14 UTC, isopov commented on src/main/java/ru/mail/park/dao/impl/UserDAOImpl.java
> +    public int deleteUser(long userId, String sessionId) {
И здесь тоже sessionId не используется.

2016-10-24 08:14 UTC, isopov commented on src/main/java/ru/mail/park/services/impl/AuthorizationServiceImpl.java
> +    private AuthorizationDAO authorizationDAO;
Что это вообще такое и какую цель преследует?

2016-10-24 14:47 UTC, isopov commented
В общем комменты к коду в таком обилии изменений искать сложно. Давайте такой список:

0. Меняем идентификатор проекта в мавене с L1.3 на что-то осмысленное
1. DataBaseConnector, AuthorizationDAO, SessionDataSet,  - удаляем полностью
2. Добавляем систему миграции БД (поверьте, с ней будет проще, чем без неё)
3.  Пишем тесты

2016-10-28 14:20 UTC, isopov commented
>Временно: Закоментированны тесты + добавлено тело ответа

В моем мозгу возникает аналогия "в обычной шапке бегать жарко и мокро от пота, но я не куплю спортивную шапку, материал которой эффективно отводит влагу, а побегу в мороз без шапки - бежать мне будет удобнее, хотя после забега я заболею менингитом и умру..."

Простите...

2016-11-06 15:55 UTC, isopov commented
Такс... ну вот, наконец, можно говорить о стиле:
1. Обилие `@SuppressWarnings("unused")` несколько настораживает (моей IDE они многие подсвечены, как ненужные) - особенно настораживает целиком на некоторых классах
2. `@Transactional` на ДАО - оно не имеет смысла практически, потому что в каждом методе этого ДАО у вас единственный запрос к базе. И традиционно границу транзакций делают на сервисном слое (а он у вас тоже есть), чтобы объединять в одну транзакцию несколько вызовов в ДАО.
3. В сервисный слой обильно протекли web-объекты HttpSession & ResponseEntity - по-хорошему их там не должно быть.
4. В моей IDE все использования ResponseEntity подсвечены предупреждением про raw types. Во многих методах этот ResponseEntity вообще лишний и можно возвращать просто тело ответа, потому что код всегда один и тот же.
5. ru.mail.park.services.impl.UserServiceImpl.idCheck(Object, long) - метод публичный, хотя используется только в этом классе, он инстансовый, хотя никак не использует состояние класса

2016-11-09 22:32 UTC, BOG8 commented
1. Найдено, только два @SuppressWarnings("unused"), которые были лишними (и то один из них стал лишним из-за правок по третьему пункту). Если убирать остальные, то моё IDE начинает подсвечивать куски кода, как неиспользуемые.
2. @Transactional на ДАО убрана, на сервис слой не добавлена по той же причине, по которой она не имеет смысла на ДАО)
3. Исправлено.
4. Найден только один метод, который всегда возвращает один и тот же код. Подправлено.
5. Исправлено. В ходе правок третьего пункта, метод idCheck перенесён в ru.mail.park.controllers.UserController.java

2016-11-10 15:24 UTC, isopov commented
Давайте пофиксим последнюю серьёзную проблему:
`DataSourceUtils.getConnection(dataSource)` - это метод для получения соединения с базой внутри спринговой транзакции. Вы сейчас без транзакций используете этот метод в продакшне (в тестах - с ними). Так что давайте всё-таки вернем @Transactional на сервисный слой.

2016-11-10 16:12 UTC, merged